export const HOME_DISCLOSURE = 'HOME_DISCLOSURE';

// PROGRESS
export const PROGRESS_SHOW = 'PROGRESS_SHOW';
export const PROGRESS_HIDE = 'PROGRESS_HIDE';

// faq
export const FAQ_GET_LIST = 'FAQ_GET_LIST';
export const FAQ_GET_CATEGORIES = 'FAQ_GET_CATEGORIES';

// NOTICE
export const NOTICE_GET_LIST = 'NOTICE_GET_LIST';
export const NOTICE_GET_DETAIL = 'NOTICE_GET_DETAIL';

// QNA
export const QNA_GET_LIST = 'QNA_GET_LIST';
export const QNA_GET_DETAIL = 'QNA_GET_DETAIL';
export const QNA_WRITE = 'QNA_WRITE';

// GET BANK
export const BANK_GET_LIST = 'BANK_GET_LIST';

// FORGOT
export const FIND_EMAIL = 'FIND_EMAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RENEW_PASSWORD = 'RENEW_PASSWORD';

// SESSION
export const SESSION_UPDATE = 'SESSION_UPDATE';

// USER
export const CHECK_PASSWORD = 'CHECK_PASSWORD';
export const CHECK_EMAIL = 'CHECK_EMAIL';

export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_FETCH = 'USER_FETCH';
export const USER_SET_DATA = 'USER_SET_DATA';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UNREGISTER = 'USER_UNREGISTER';
export const USER_CLEAR = 'USER_CLEAR';
export const USER_UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD';
export const USER_CERTIFICATE = 'USER_CERTIFICATE';
export const USER_CONTACT_REQUEST = 'USER_CONTACT_REQUEST';
export const USER_CONTACT_VERIFY = 'USER_CONTACT_VERIFY';
export const USER_GET_DASHBOARD = 'USER_GET_DASHBOARD';
export const USER_SESSION = 'USER_SESSION';

// USER-BANK
export const USER_GET_BANK_INFO = 'USER_GET_BANK_INFO';
export const USER_BANK_WITHDRAW = 'USER_BANK_WITHDRAW';
export const USER_GET_BANK_HISTORY = 'USER_GET_BANK_HISTORY';
export const USER_UPDATE_BANK = 'USER_UPDATE_BANK';
export const USER_GET_V_BANK_DEPOSIT = 'USER_GET_V_BANK_DEPOSIT';

// USER-INVEST
export const USER_INVEST_SUMMARY = 'USER_INVEST_SUMMARY';
export const USER_INVEST_GET_LIST = 'USER_GET_INVESTS';

// USER-LOAN
export const USER_LOAN_GET_LIST = 'USER_LOAN_GET_LIST';
export const USER_LOAN_DETAIL = 'USER_LOAN_DETAIL';
export const USER_LOAN_SCHEDULE = 'USER_INVEST_SCHEDULE';

// SECURITY
export const SECURITY_REQUEST = 'SECURITY_REQUEST';

// INVEST
export const INVEST_GET_LIST = 'INVEST_GET_LIST';
export const INVEST_GET_DETAIL = 'INVEST_GET_DETAIL';
export const INVEST_JOIN = 'INVEST_JOIN';
export const INVEST_CANCEL = 'INVEST_CANCEL';
export const INVEST_PREVIEW = 'INVEST_PREVIEW';
export const INVEST_CERT_DOWNLOAD = 'INVEST_CERT_DOWNLOAD';
